# Generated by Django 5.1 on 2024-08-15 17:30

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Arquivo')),
                ('codigo', models.CharField(default='000', max_length=100, verbose_name='Codigo')),
                ('versao', models.CharField(default='000', max_length=50, verbose_name='Versao')),
                ('opcao', multiselectfield.db.fields.MultiSelectField(choices=[('ALMOXARIFADO', 'ALMOXARIFADO'), ('COMERCIAL', 'COMERCIAL'), ('COMPRAS', 'COMPRAS'), ('CONSERVAÇÃO', 'CONSERVAÇÃO'), ('CONTROLADORIA', 'CONTROLADORIA'), ('CONTROLE', 'CONTROLE'), ('DEPARTAMENTO PESSOAL', 'DEPARTAMENTO PESSOAL'), ('DIREÇÃO', 'DIREÇÃO'), ('DPOB', 'DPOB'), ('EDITOR SESMT', 'EDITOR SESMT'), ('ENGENHARIA', 'ENGENHARIA'), ('FINANCEIRO', 'FINANCEIRO'), ('FISCAL', 'FISCAL'), ('MARKETING', 'MARKETING'), ('OFICINA', 'OFICINA'), ('RECRUTAMENTO', 'RECRUTAMENTO'), ('SESMT', 'SESMT'), ('SUPRIMENTOS', 'SUPRIMENTOS'), ('TODOS', 'TODOS')], default='000', max_length=300, verbose_name='Opções')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('arquivopdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Arquivo PDF')),
                ('tipo', multiselectfield.db.fields.MultiSelectField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], default='000', max_length=300, verbose_name='Tipo')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', multiselectfield.db.fields.MultiSelectField(choices=[('ALMOXARIFADO', 'ALMOXARIFADO'), ('COMERCIAL', 'COMERCIAL'), ('COMPRAS', 'COMPRAS'), ('CONSERVAÇÃO', 'CONSERVAÇÃO'), ('CONTROLADORIA', 'CONTROLADORIA'), ('CONTROLE', 'CONTROLE'), ('DEPARTAMENTO PESSOAL', 'DEPARTAMENTO PESSOAL'), ('DIREÇÃO', 'DIREÇÃO'), ('DPOB', 'DPOB'), ('EDITOR SESMT', 'EDITOR SESMT'), ('ENGENHARIA', 'ENGENHARIA'), ('FINANCEIRO', 'FINANCEIRO'), ('FISCAL', 'FISCAL'), ('MARKETING', 'MARKETING'), ('OFICINA', 'OFICINA'), ('RECRUTAMENTO', 'RECRUTAMENTO'), ('SESMT', 'SESMT'), ('SUPRIMENTOS', 'SUPRIMENTOS'), ('TODOS', 'TODOS')], default='TODOS', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
