# Generated by Django 5.1 on 2024-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='disponivel_para_download',
            field=models.BooleanField(default=False),
        ),
    ]
