# Generated by Django 5.1 on 2024-08-19 17:45

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_arquivo_disponivel_para_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='opcao',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ALMOXARIFADO', 'ALMOXARIFADO'), ('COMERCIAL', 'COMERCIAL'), ('COMPRAS', 'COMPRAS'), ('CONSERVAÇÃO', 'CONSERVAÇÃO'), ('CONTROLADORIA', 'CONTROLADORIA'), ('CONTROLE', 'CONTROLE'), ('DEPARTAMENTO PESSOAL', 'DEPARTAMENTO PESSOAL'), ('DIREÇÃO', 'DIREÇÃO'), ('DPOB', 'DPOB'), ('EDITOR SESMT', 'EDITOR SESMT'), ('ENGENHARIA', 'ENGENHARIA'), ('FINANCEIRO', 'FINANCEIRO'), ('FISCAL', 'FISCAL'), ('MARKETING', 'MARKETING'), ('OBRAS', 'OBRAS'), ('OFICINA', 'OFICINA'), ('RECRUTAMENTO', 'RECRUTAMENTO'), ('SESMT', 'SESMT'), ('SUPRIMENTOS', 'SUPRIMENTOS'), ('TODOS', 'TODOS')], default='000', max_length=300, verbose_name='Opções'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word')], default='pdf', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='setor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ALMOXARIFADO', 'ALMOXARIFADO'), ('COMERCIAL', 'COMERCIAL'), ('COMPRAS', 'COMPRAS'), ('CONSERVAÇÃO', 'CONSERVAÇÃO'), ('CONTROLADORIA', 'CONTROLADORIA'), ('CONTROLE', 'CONTROLE'), ('DEPARTAMENTO PESSOAL', 'DEPARTAMENTO PESSOAL'), ('DIREÇÃO', 'DIREÇÃO'), ('DPOB', 'DPOB'), ('EDITOR SESMT', 'EDITOR SESMT'), ('ENGENHARIA', 'ENGENHARIA'), ('FINANCEIRO', 'FINANCEIRO'), ('FISCAL', 'FISCAL'), ('MARKETING', 'MARKETING'), ('OBRAS', 'OBRAS'), ('OFICINA', 'OFICINA'), ('RECRUTAMENTO', 'RECRUTAMENTO'), ('SESMT', 'SESMT'), ('SUPRIMENTOS', 'SUPRIMENTOS'), ('TODOS', 'TODOS')], default='TODOS', max_length=300),
        ),
    ]
