# Generated by Django 5.1 on 2024-08-20 17:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_arquivo_opcao_alter_userprofile_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='opcao',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ALMOXARIFADO', 'ALMOXARIFADO'), ('COMERCIAL', 'COMERCIAL'), ('COMPRAS', 'COMPRAS'), ('CONSERVAÇÃO', 'CONSERVAÇÃO'), ('CONTROLADORIA', 'CONTROLADORIA'), ('CONTROLE', 'CONTROLE'), ('DEPARTAMENTO PESSOAL', 'DEPARTAMENTO PESSOAL'), ('DIREÇÃO', 'DIREÇÃO'), ('DPOB', 'DPOB'), ('EDITOR SESMT', 'EDITOR SESMT'), ('ENGENHARIA', 'ENGENHARIA'), ('FINANCEIRO', 'FINANCEIRO'), ('FISCAL', 'FISCAL'), ('MARKETING', 'MARKETING'), ('OBRAS', 'OBRAS'), ('OFICINA', 'OFICINA'), ('QUALIDADE', 'QUALIDADE'), ('RECRUTAMENTO', 'RECRUTAMENTO'), ('SESMT', 'SESMT'), ('SUPRIMENTOS', 'SUPRIMENTOS'), ('TODOS', 'TODOS')], default='000', max_length=300, verbose_name='Opções'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='setor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ALMOXARIFADO', 'ALMOXARIFADO'), ('COMERCIAL', 'COMERCIAL'), ('COMPRAS', 'COMPRAS'), ('CONSERVAÇÃO', 'CONSERVAÇÃO'), ('CONTROLADORIA', 'CONTROLADORIA'), ('CONTROLE', 'CONTROLE'), ('DEPARTAMENTO PESSOAL', 'DEPARTAMENTO PESSOAL'), ('DIREÇÃO', 'DIREÇÃO'), ('DPOB', 'DPOB'), ('EDITOR SESMT', 'EDITOR SESMT'), ('ENGENHARIA', 'ENGENHARIA'), ('FINANCEIRO', 'FINANCEIRO'), ('FISCAL', 'FISCAL'), ('MARKETING', 'MARKETING'), ('OBRAS', 'OBRAS'), ('OFICINA', 'OFICINA'), ('QUALIDADE', 'QUALIDADE'), ('RECRUTAMENTO', 'RECRUTAMENTO'), ('SESMT', 'SESMT'), ('SUPRIMENTOS', 'SUPRIMENTOS'), ('TODOS', 'TODOS')], default='TODOS', max_length=300),
        ),
    ]
